repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # or the latest stable version
    hooks:
      - id: flake8
        args: [--max-line-length=88, --ignore=E203,E501,W503]  # optional arguments
