repos:
  - repo: local
    hooks:
      - id: flake8
        name: Run flake8
        entry: bash -c "flake8"
        language: python
        pass_filenames: false
        files: ^.py/
        types: [python]
